#Suvodeep Das
#A1
Roll 90

##Array creation & Array Concatenation & Converting to DataFrame


In [ ]:
import numpy as np
import pandas as pd
a = np.array([[1,5,9], [2,6,10]])
b = np.array([[3,7,11], [4,8,12]])
c = np.concatenate((a,b), axis=0)
df = pd.DataFrame(c, columns = ['Column A','Column B','Column C'])
print(c)
print(df)
print(type(df))

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
   Column A  Column B  Column C
0         1         5         9
1         2         6        10
2         3         7        11
3         4         8        12
<class 'pandas.core.frame.DataFrame'>


##Trigonometric functions

In [ ]:
import numpy as np
from numpy import pi
array1 = np.array ( [30, 60, 90])
np.sin (array1*np.pi/180)

array([0.5      , 0.8660254, 1.       ])

##Functions For rounding Decimals to the desired Precision


In [ ]:
np.around(array1) #around function


array([30, 60, 90])

In [ ]:
np.floor(array1) #floor function

array([30., 60., 90.])

In [ ]:
np.ceil(array1) #ceil function

array([30., 60., 90.])

##Sorting & Searching Functions

In [ ]:
arr=np.array([94,56,78,94,65,63,78,12,10,99])
np.sort(arr)

array([10, 12, 56, 63, 65, 78, 78, 94, 94, 99])

In [ ]:
np.where(arr>10)

(array([0, 1, 2, 3, 4, 5, 6, 7, 9]),)

##Statistical Functions

In [ ]:
z=np.array([10,20,202,15,10,30,56.8,88,97.96,85.012,100])
np.mean(z)

64.97927272727271

In [ ]:
np.median(z)

56.8

In [ ]:
np.std(z)

55.495353628751346

In [ ]:
np.var(z)

3079.7342743801655

##Pandas Implementation


In [ ]:
import pandas as pd
url="https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
data = pd.read_csv(url)
data.shape

(891, 12)

In [ ]:
row=data.shape[0]
print(row)

891


In [ ]:
col=data.shape[1]
print(col)

12


In [ ]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
data.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [ ]:
data.tail()

PassengerId  Survived  Pclass  ...   Fare Cabin  Embarked
886          887         0       2  ...  13.00   NaN         S
887          888         1       1  ...  30.00   B42         S
888          889         0       3  ...  23.45   NaN         S
889          890         1       1  ...  30.00  C148         C
890          891         0       3  ...   7.75   NaN         Q

[5 rows x 12 columns]

In [ ]:
np.mean(data[["PassengerId"]])

PassengerId    446.0
dtype: float64

In [ ]:
np.median(data[["PassengerId"]])

446.0

In [ ]:
np.var(data[["PassengerId"]])

PassengerId    66156.666667
dtype: float64

In [ ]:
np.std(data[["PassengerId"]])

PassengerId    257.209383
dtype: float64